export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const LOAD_UNIVERSITIES_SUCCESS = "LOAD_UNIVERSITIES_SUCCESS";
export const LOAD_UNIVERSITIES_FAIL = "LOAD_UNIVERSITIES_FAIL";

export const LOAD_PROGRAMS_SUCCESS = "LOAD_PROGRAMS_SUCCESS";
export const LOAD_PROGRAMS_FAIL = "LOAD_PROGRAMS_FAIL";

export const CLEAR_PROGRAMS = "CLEAR_PROGRAMS";

export const FILTER = "FILTER";
