export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const LOAD_UNIVERSITIES_SUCCESS = 'LOAD_UNIVERSITIES_SUCCESS';
export const LOAD_UNIVERSITIES_FAIL = 'LOAD_UNIVERSITIES_FAIL';

export const LOAD_UNIVERSITY_SUCCESS = 'LOAD_UNIVERSITY_SUCCESS';
export const LOAD_UNIVERSITY_FAIL = 'LOAD_UNIVERSITY_FAIL';
